const ACTION_TYPES = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  //
  GET_ARTICLE_START: "GET_ARTICLE_START",
  GET_ARTICLE_SUCCESS: "GET_ARTICLE_SUCCESS",
  GET_ARTICLE_FAILURE: "GET_ARTICLE_FAILURE",
  CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
};
export default ACTION_TYPES;
